In [1]:
import numpy as np

In [2]:
?np.arange

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [3]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
my_matrix = np.diag(np.arange(10, 0, -1))
sum(sum(my_matrix))

55

In [37]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine(matrix, user):

    max_cos_length = 0
    max_user_index = 0
    
    for user in users_stats:
        cos_length = np.dot(user, next_user_stats) / (np.linalg.norm(user) * np.linalg.norm(next_user_stats))
        if cos_length > max_cos_length: 
            max_cos_length = cos_length            
            user_index = max_user_index
        max_user_index += 1
    
    return user_index

        

print(cosine(users_stats, next_user_stats))
#cosine(users_stats, next_user_stats)

7


In [41]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

np.linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [43]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
a

array([[4, 2, 1],
       [1, 3, 0],
       [0, 5, 4]])